version: '3.1'

services:
  backend:
    image: mefti/ruby:2.6.6
    container_name: gestao-imobiliaria-backend
    user: mefti:mefti
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./backend/:/app
      - gems:/.gems
    environment:
      - BASE_HREF=/api
      - RAILS_ENV=development
    env_file:
      - ./backend/.env

  frontend:
    image: mefti/node:12.16-angular-cli-9.0.4
    container_name: gestao-imobiliaria-frontend
    user: node:node
    stdin_open: true
    tty: true
    ports:
      - 4200:4200
    volumes:
      - ./frontend/:/app

volumes:
  gems: